================================
ORDERSYSTEM (Exercise)
================================

# We need to define ENUM type separately in postgreSQL
CREATE TYPE colors AS ENUM('Cherry', 'Natural Ash', 'White Ash', 'Red Oak', 'Natural Oak', 'Walnut');

CREATE TABLE PRODUCT(
PRODUCT_ID INTEGER NOT NULL, 
PRODUCT_DESCRIPTION VARCHAR(50), 
PRODUCT_FINISH colors,
STANDARD_PRICE DECIMAL(8,2),
CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_ID));

CREATE TABLE CUSTOMER(
CUSTOMER_ID INTEGER NOT NULL, 
CUSTOMER_NAME VARCHAR(25) NOT NULL, 
CUSTOMER_ADDRESS VARCHAR(30),
CITY VARCHAR(20),
POSTAL_CODE VARCHAR(9),
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE ORDERT(
    ORDER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CUSTOMER_ID INTEGER NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_ID),
    CONSTRAINT ORDER_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

CREATE TABLE ORDER_LINE(
    ORDER_ID INTEGER NOT NULL, 
    PRODUCT_ID INTEGER NOT NULL, 
    ORDERED_QUANTITY INTEGER,
    CONSTRAINT ORDER_LINE_PK PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT ORDER_LINE_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERT(ORDER_ID),
    CONSTRAINT ORDER_LINE_FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));


\copy customer FROM '/home/ordersystem/customer.csv' DELIMITER ',' CSV;

\copy product FROM '/home/ordersystem/product.csv' DELIMITER ',' CSV;

\copy ordert FROM '/home/ordersystem/order.csv' DELIMITER ',' CSV;

\copy order_line FROM '/home/ordersystem/order_line.csv' DELIMITER ',' CSV;

#========== Ignore the following lines just for testing some integrity ============
INSERT INTO customer (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, CITY, POSTAL_CODE) VALUES ('10001', 'จอน', 'ปทุมวัน','กรุงเทพ', '10330');
INSERT INTO product (PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_FINISH, STANDARD_PRICE) VALUES ('0001', 'Table', 'Red Oak', '2000'), ('0002', 'Chair', 'Walnut', '5000');
INSERT INTO ordert (ORDER_ID, CUSTOMER_ID) VALUES ('001', '10001');
INSERT INTO order_line (ORDER_ID, PRODUCT_ID, ORDERED_QUANTITY) VALUES ('001', '0001', '1'), ('001', '0002', '5');
INSERT INTO ordert (ORDER_ID, CUSTOMER_ID) VALUES ('002', '10001');
INSERT INTO order_line (ORDER_ID, PRODUCT_ID, ORDERED_QUANTITY) VALUES ('002', '0001', '10');

SELECT * FROM customer NATURAL JOIN ordert NATURAL JOIN order_line; 

DELETE FROM customer WHERE CUSTOMER_ID ='10001'; # error due to referential integrity constraints
