version: "3.9"

networks:
  monitoring:
    driver: bridge

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter
    deploy:
      resources:
        limits:
          cpus: "0.25"
    networks:
      - monitoring
    ports:
      - "9100"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
