global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "activity2-node-exporter-1:9100"
          - "activity2-node-exporter-2:9100"
          - "activity2-node-exporter-3:9100"
